# Generated by Django 2.2.3 on 2019-08-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuitId', models.IntegerField()),
                ('circuitRef', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('alt', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverId', models.IntegerField()),
                ('driverRef', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('code', models.CharField(max_length=3)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverStandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverStandingsId', models.IntegerField()),
                ('raceId', models.IntegerField()),
                ('driverId', models.IntegerField()),
                ('points', models.FloatField()),
                ('position', models.IntegerField()),
                ('positionText', models.CharField(max_length=255)),
                ('wins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='F1Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='LapTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceId', models.IntegerField()),
                ('driverId', models.IntegerField()),
                ('lap', models.IntegerField()),
                ('position', models.IntegerField()),
                ('time', models.CharField(max_length=255)),
                ('milliseconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceId', models.IntegerField()),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('circuitId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultId', models.IntegerField()),
                ('raceId', models.IntegerField()),
                ('driverId', models.IntegerField()),
                ('constructorId', models.IntegerField()),
                ('number', models.IntegerField()),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField()),
                ('positionText', models.CharField(max_length=255)),
                ('positionOrder', models.IntegerField()),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(max_length=255)),
                ('milliseconds', models.IntegerField()),
                ('fastestLap', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('fastestLapTime', models.CharField(max_length=255)),
                ('fastestLapSpeed', models.CharField(max_length=255)),
                ('statusId', models.IntegerField()),
            ],
        ),
    ]
