# Generated by Django 2.2.3 on 2019-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuits',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driverstandings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='laptimes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='races',
            name='id',
        ),
        migrations.RemoveField(
            model_name='results',
            name='id',
        ),
        migrations.AlterField(
            model_name='circuits',
            name='circuitId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='driverId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverstandings',
            name='driverStandingsId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laptimes',
            name='raceId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='races',
            name='raceId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='results',
            name='resultId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
