# Generated by Django 2.2.3 on 2019-08-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_auto_20190802_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptimes',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptimes',
            name='raceId',
            field=models.IntegerField(),
        ),
    ]
