# Generated by Django 2.2.3 on 2019-08-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_auto_20190802_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='circuitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.Circuits'),
        ),
    ]
