# Generated by Django 2.2.3 on 2019-08-02 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_auto_20190802_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='driverId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.Drivers'),
        ),
        migrations.AlterField(
            model_name='results',
            name='raceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.Races'),
        ),
    ]
